### ISSUE TITLE
How to compute the stiffness matrix K?

### ISSUE THREAD

**Issue by FantasyVR** [YuCrazing/Taichi#1]
When computing `dP(F:\delta F)` ,  there are some differences between your implementation and the [SIGGRAPH 2012 FEM Course](http://femdefo.org/)
https://github.com/YuCrazing/Taichi/blob/a8df2239e359550bd63ec3320a6a7a9b39524fa5/fem_3d_imp/fem-3d-implicit.py#L263

Why do you re-compute dF in the for-loop rather than using the already computed dF?

I tried to change some code according to algorithm 2 in  [SIGGRAPH 2012 FEM Course](http://femdefo.org/) based on your code. The simulation still works.
```
            for n in range(4):
                for dim in range(self.dim):
                    for i in ti.static(range(self.dim)):
                        for j in ti.static(range(self.dim)):
                            dF = self.dF[e,n,dim]
                            dF_T = dF.transpose()
                            dTr = (F_1 @ dF).trace()
                            dP_dFij = self.mu * dF + (self.mu - self.la * ti.log(J)) * F_1_T @ dF_T @ F_1_T + self.la * dTr * F_1_T
                            self.dP[e, n, dim] += dP_dFij 
```

**Comment by YuCrazing** [comment]
`self.dF` means dF/dx, and the second `dF` means dF/dF_{ij}.

And the meaning of my code is

![png latex-2](https://user-images.githubusercontent.com/8120108/90956179-b4fece00-e4b6-11ea-89be-5cecc5c43dfa.png)

You can check whether it is equivalent to your code. 🙂

**Comment by devenguo** [comment]
Same question here. I also have problems computing dP/dF. Sifakis's implementation is using the stress differential (Kdx) rather than the explicit K. And it seems quite difficult to get the symbolic form of the Hessian. Could you please show me the explicit form of the K? And thanks for such an interesting demo.
